version: "3.9"
services:
  microservicio:
    container_name: microservicio
    image: jhanherrera/api-microservicio:v1
    build:
      context: .
    ports:
      - "4002" 
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=4002  
    networks:
      - microservicio

  balanceador:
    container_name: balanceador-carga
    image: balanceador-carga:v1
    build:
      context: ./balanceador
    ports:
      - "4004:80"
    networks:
      - microservicio

networks:
  microservicio: